// httpClient 테스트용

// index 수동 생성 ( 일단은 스프링에서 자동 생성해준다. )
PUT http://localhost/search
Content-Type: application/json

{
  "settings": {
     "analysis": {
        "analyzer": {
           "korean_analyzer": {
              "type": "nori",
              "stopwords": "_korean_"
           }
        },
     }
  },
  "mappings": {
     "properties" : {
        "id" : { "type":"integer" },
        "title" : { "type":"text", "analyzer":"korean_analyzer" },
        "description": { "type":"text", "analyzer":"korean_analyzer" },
        "createdAt": { "type":"date", "format":"epoch_second" },
        "updatedAt": { "type":"date", "format":"epoch_second" }
     }
  }
}

// index mapping 정보 조회
GET http://localhost:9200/search/_mapping HTTP/1.1
Content-Type: application/json

// index setting 정보 조회
GET http://localhost:9200/search/_setting
Content-Type: application/json

// 인덱스 삭제
DELETE http://localhost:9200/search
Content-Type: application/json