spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/boot?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false
      username: boot
      password: boot
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    database: MYSQL
    show-sql: true
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9093
spring-doc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    enabled: true
logging:
  level:
    root: debug #INFO


tensing:
  jwt:
    accessToken:
      tokenName: Authorization
      secretKey: Q4NSl604sgydJj1awEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSf4XXyYJkal13eqgB0F5Bqaa
      expirationInMs: 1296000000 # 1000 * 60 * 60 * 24 * 1
      signatureAlgorithm: HS512
    refreshToken:
      tokenName: Authorization
      secretKey: e3NSl604sgydJj1awEkR3ycUeR4uUet7WJraD7EN3O9aVM4yyYuHxMEbSf4XXyYJkal3seqgB0F5Bqaa
      expirationInMs: 1296000000 # 1000 * 60 * 60 * 24 * 30
      signatureAlgorithm: HS512
  elasticsearch:
    servers: localhost:9200