spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test
      username: sa
      password: null
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    generate-ddl: true
    properties:
      default_batch_fetch_size: 1000 # N+1 문제 발생시 in 절로 1000개 단위로 나눠서 호출
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9093
  elasticsearch:
    uris: localhost:9200

logging:
  level:
    root: INFO
    org.apache.kafka: error
tensing:
  jwt:
    accessToken:
      tokenName: Authorization
      secretKey: Q4NSl604sgydJj1awEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSf4XXyYJkal13eqgB0F5Bqaa
      expirationInMs: 1296000000 # 1000 * 60 * 60 * 24 * 1
      signatureAlgorithm: HS512
    refreshToken:
      tokenName: Authorization
      secretKey: e3NSl604sgydJj1awEkR3ycUeR4uUet7WJraD7EN3O9aVM4yyYuHxMEbSf4XXyYJkal3seqgB0F5Bqaa
      expirationInMs: 1296000000 # 1000 * 60 * 60 * 24 * 30
      signatureAlgorithm: HS512
  elasticsearch:
    servers: localhost:9200
