server:
  port: 80
#  ssl:
#    key-alias: gensing_keystore
#    key-password: gensing
#    key-store: classpath:cert/gensing_keystore.p12
#    key-store-password: gensing
#    trust-store: classpath:cert/gensing_truststore.p12
#    trust-store-password: gensing
  shutdown: graceful # kill -15 시 안전하게 종료

spring:
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 30 # kill -15 시 30초 까지 기존 도는 프로세스를 기다려준다.
  mvc:
    static-path-pattern: /static/**
logging:
  file: ./log
  charset:
    console: UTF-8
    file: UTF-8
  config: classpath:logback-spring-${spring.profiles.active}.xml
