version: '2'
services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ./../docker-data/mariadb/data:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: boot
      MYSQL_USER: boot
      MYSQL_PASSWORD: boot
    networks:
      - es-bridge
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --port 6379
    ports:
      - 6379:6379
  es:
    build:
      context: ./es/
      args:
        ELK_VERSION: 7.15.2
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=boot
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge
  logstash:
    build:
      context: ./logstash/
      args:
        ELK_VERSION: 7.15.2
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/pipeline.yml:/usr/share/logstash/config/pipeline.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/jars:/usr/share/logstash/jars
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es-bridge
    depends_on:
      - es
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    networks:
      - es-bridge
    depends_on:
      - es
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 21812:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 21812
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:21812
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true # 실제 환경에서는 사용하지 말고, 직접 생성하시오?
    volumes:
      - ./../docker-data/kafka/data:/var/lib/kafka/data

networks:
  es-bridge:
    driver: bridge